import { NextResponse } from "next/server";

export async function POST(req) {
  try {
    const form = await req.formData();
    const file = form.get("file");

    if (!file) {
      return NextResponse.json(
        { error: "No file provided" },
        { status: 400 }
      );
    }

    if (!process.env.SIGHTENGINE_USER || !process.env.SIGHTENGINE_SECRET) {
      return NextResponse.json(
        { error: "Sightengine API credentials not configured" },
        { status: 500 }
      );
    }

    // Use native FormData (available in Node.js 18+)
    // Create a File object from the buffer for proper multipart encoding
    const buffer = await file.arrayBuffer();
    const fileBlob = new Blob([buffer], { 
      type: file.type || "image/jpeg" 
    });
    
    // Create a File object (File extends Blob with name property)
    const fileObj = new File([fileBlob], file.name || "image.jpg", {
      type: file.type || "image/jpeg"
    });
    
    const formData = new FormData();
    formData.append("media", fileObj);
    
    // Include genai model for AI detection (ai_generated score)
    const url = `https://api.sightengine.com/1.0/check.json?models=nudity,offensive,face-attributes,genai&api_user=${process.env.SIGHTENGINE_USER}&api_secret=${process.env.SIGHTENGINE_SECRET}`;

    const result = await fetch(url, {
      method: "POST",
      body: formData,
    });

    if (!result.ok) {
      const errorText = await result.text();
      return NextResponse.json(
        { error: `Sightengine API error: ${result.status}`, details: errorText },
        { status: result.status }
      );
    }

    const data = await result.json();
    
    // Transform Sightengine response to include AI detection in expected format
    const aiGeneratedScore = data.type?.ai_generated ?? null;
    
    // Sightengine returns 0.0-1.0 where higher = more likely AI-generated
    // Using a threshold of 0.3 for better sensitivity
    // If score is 0.85, that means 85% likely AI, so isAI should be true
    const isAI = aiGeneratedScore !== null ? aiGeneratedScore > 0.3 : null;
    
    // For confidence display, use the ai_generated score directly (0.0-1.0)
    // Higher score = more confident it's AI
    const confidenceForDisplay = aiGeneratedScore !== null ? aiGeneratedScore : 0;
    
    // Add AI detection data in format compatible with frontend
    const responseData = {
      ...data,
      // AI Detection fields (for compatibility with Gemini format)
      isAI: isAI,
      aiConfidence: confidenceForDisplay, // Use raw score for confidence
      description: aiGeneratedScore !== null 
        ? `This image is ${isAI ? 'likely AI-generated' : 'likely a real photo'}. AI generation probability: ${(aiGeneratedScore * 100).toFixed(1)}%`
        : 'AI detection analysis completed.',
      keyElements: [],
      fullAnalysis: aiGeneratedScore !== null
        ? `AI Detection Analysis (Sightengine):\n\n` +
          `Status: ${isAI ? 'AI Generated' : 'Real Photo'}\n` +
          `AI Generation Probability: ${(aiGeneratedScore * 100).toFixed(1)}%\n` +
          `Raw Score: ${aiGeneratedScore.toFixed(4)} (0.0 = Real, 1.0 = AI)\n` +
          `Threshold Used: 0.3 (scores above this are considered AI-generated)\n\n` +
          `The Sightengine AI detection model has analyzed this image and determined that it is ${isAI ? 'likely generated by artificial intelligence' : 'likely a genuine photograph'} with an AI generation probability of ${(aiGeneratedScore * 100).toFixed(1)}%. ` +
          `${isAI ? 'AI-generated images typically show certain patterns, artifacts, or characteristics that distinguish them from real photographs.' : 'Real photographs typically show natural variations, realistic lighting, and authentic details that are characteristic of genuine photography.'}`
        : 'AI detection analysis was completed, but no score was available. Please ensure the "genai" model is enabled in your Sightengine API request.',
    };
    
    return NextResponse.json({ model: "sightengine", data: responseData });
  } catch (error) {
    console.error("Sightengine API error:", error);
    return NextResponse.json(
      { error: "Failed to process request", message: error.message },
      { status: 500 }
    );
  }
}
